on:
  push:
    branches:
      - main
      - release/*'
  pull_request:
    branches:
      - main
  schedule:
      - cron: "0 2 * * 1-5"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: python my_script.py
